import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from './contexts/AuthContext';
import { ProfileProvider } from "./contexts/ProfileContext";
import { MarketProvider } from "./contexts/MarketContext";
import { ExerciserProvider } from "./contexts/ExerciserContext";
import { InvestorProvider } from "./contexts/InvestorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProfileProvider>
            <InvestorProvider>
              <ExerciserProvider>
                <MarketProvider>
                  {children}
                </MarketProvider>
              </ExerciserProvider>
            </InvestorProvider>
          </ProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
